version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: offerapp-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: offerappprodb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: